---
# Copyright (c) 2020 Contributors to Smart-Data-Models
# see https://github.com/smart-data-models/dataModel.Device

components: 
  schemas: 
    Device: 
      $ref: "https://smart-data-models.github.io/dataModel.Device/Device/model.yaml#/Device"
    DeviceCategory: 
      $ref: "https://smart-data-models.github.io/data-models/saref-terms.yaml#/Categories"
    SupportedProtocol: 
      $ref: "https://smart-data-models.github.io/dataModel.Device/model.yaml#/SupportedProtocol"
info: 
  description: |
      An apparatus (hardware + software + firmware) intended to accomplish a
      particular task (sensing the environment, actuating, etc.). A Device is a
      tangible object which contains some logic and is producer and/or consumer of
      data. A Device is always assumed to be capable of communicating electronically
      via a network.
      
      This data model has been partially developed in cooperation with mobile
      operators and the [GSMA](https://www.gsma.com/iot/iot-big-data/).
      
      This data model reuses concepts coming from the
      [SAREF Ontology](http://www.etsi.org/deliver/etsi_ts/103200_103299/103264/01.01.01_60/ts_103264v010101p.pdf)
      part of [ETSI](http://www.etsi.org) standards.
  title: Device
  version: "1.0.0"
openapi: "3.0.0"
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Device
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Device/Device/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Device/Device/examples/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format\n"
    name: ngsi-ld
